apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ace-tekton-trig
spec:
  serviceAccountName: pipeline-account
  triggers:
  - bindings:
    - name: ace-tekton-trig
    template:
      name: ace-tekton-trig
