apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests
spec:
  resources:
    inputs:
      - {type: git, name: source}
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
  steps:
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          sed -i 's/dep-namespace/bma-prod/g' $(inputs.params.manifest_dir)/deployment.yaml
          sed -i 's/dep-namespace/bma-prod/g' $(inputs.params.manifest_dir)/routehttp.yaml
          sed -i 's/dep-namespace/bma-prod/g' $(inputs.params.manifest_dir)/routehttps.yaml
          sed -i 's/dep-name/bmaprod/g' $(inputs.params.manifest_dir)/configmap.yaml
          sed -i 's/dep-name/bmaprod/g' $(inputs.params.manifest_dir)/deployment.yaml
          sed -i 's/dep-name/bmaprod/g' $(inputs.params.manifest_dir)/job.yaml
          sed -i 's/dep-name/bmaprod/g' $(inputs.params.manifest_dir)/routehttp.yaml
          sed -i 's/dep-name/bmaprod/g' $(inputs.params.manifest_dir)/routehttps.yaml
          sed -i 's/dep-name/bmaprod/g' $(inputs.params.manifest_dir)/service1.yaml
          sed -i 's/dep-name/bmaprod/g' $(inputs.params.manifest_dir)/service2.yaml
          oc apply -f $(inputs.params.manifest_dir)
          echo -----------------------------------
