apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    release: bmaqa
  name: bmaqa-ibm-ace-server-icp4i-prod-rolebinding
  namespace: bma-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bmaqa-ibm-ace-server-icp4i-prod-role
subjects:
- kind: ServiceAccount
  name: bmaqa-ibm-ace-server-icp4i-prod-serviceaccount
  namespace: bma-qa
