apiVersion: v1
kind: Service
metadata:
  env:
  - name: dep-name
  annotations:
    prometheus.io/port: "9483"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: dep-name
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ibm-ace-server-icp4i-prod
    helm.sh/chart: ibm-ace-server-icp4i-prod
    release: dep-name
  name: dep-name-ibm-ace-server-icp4i-prod-ace-metrics
spec:
  ports:
  - port: 9483
    protocol: TCP
    targetPort: 9483
  selector:
    app.kubernetes.io/instance: dep-name
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ibm-ace-server-icp4i-prod
    helm.sh/chart: ibm-ace-server-icp4i-prod
    release: dep-name
  sessionAffinity: None
  type: ClusterIP
